version: "3.8"
services:
  nginx:
    container_name: "nginx"
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
      - ./certs:/etc/nginx/certs
    networks:
      - webnet

networks:
  webnet:
