version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:433"
    volumes:
      - ./html:/var/www/html
      - ./certs:/etc/nginx/certs
    networks:
      - webnet

networks:
  webnet:
